### ISSUE TITLE
Please add retain flag

### ISSUE THREAD

**Issue by derlangemarkus** [ltspicer/heizoel24.mex#2]
Hey there! Thanks for this script. With it I was able to add MEX into my Home Assistant. YEAH!!!

But I added the Retain-Flag by changing line 62 to
`client.publish("MEX/" + topic, wert, 0, True)`

Without this change the values were set to "unknown" after restarting Home Assistant. Now the latest values stay persistent. Maybe this would be a good change for everybody not only for those who used Home Assistant. 

Sadly I am not able to create a pull request at my current computer settings so I just commented here. Please feel free to ignore/delete my comment here.

**Comment by ltspicer** [comment]
Danke. Ich habe das der README hinzugefügt.

**Comment by ltspicer** [comment]
Retain-flag im Script integriert.
Danke für die wichtige Info ;)

**Comment by wikando-mo** [comment]
Danke!
